[package]
name = "bucket"
edition = "2024"
version = "0.1.0"
license = "MIT"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "testnet-v1.80.1", override = true }
suins = { git = "https://github.com/MystenLabs/suins-contracts.git", subdir = "packages/suins", rev = "692a12c02260fd4abecf1630d33db819e4bcadef" }

[addresses]
bucket = "0x0"
