/**
 * Generates typed viem ABIs from Foundry artifacts into `packages/sdk/src/abi/generated.ts`.
 * Run after `forge build`: `pnpm abi`.
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..', '..')
const out = join(root, 'contracts', 'evm', 'out')
const target = join(root, 'packages', 'sdk', 'src', 'abi', 'generated.ts')

const artifacts: ReadonlyArray<readonly [exportName: string, file: string, contract: string]> = [
  ['bucketControllerAbi', 'BucketController.sol', 'BucketController'],
  ['bucketCapabilitiesAbi', 'BucketCapabilities.sol', 'BucketCapabilities'],
  ['bucketAuthorityAbi', 'BucketAuthority.sol', 'BucketAuthority'],
  ['bucketSwapVmRouterAbi', 'BucketSwapVMRouter.sol', 'BucketSwapVMRouter'],
  ['bucketPriceFeedAbi', 'BucketReferencePriceFeed.sol', 'BucketReferencePriceFeed'],
  ['bucketTestTokenAbi', 'BucketTestToken.sol', 'BucketTestToken'],
  ['aquaAbi', 'IAqua.sol', 'IAqua'],
  ['permissionedRegistryAbi', 'IPermissionedRegistry.sol', 'IPermissionedRegistry'],
  ['bucketCapabilityGuardErrorsAbi', 'BucketCapabilityGuard.sol', 'BucketCapabilityGuard'],
  ['bucketQuoteErrorsAbi', 'BucketQuote.sol', 'BucketQuote'],
  ['bucketSpendLimitErrorsAbi', 'BucketSpendLimit.sol', 'BucketSpendLimit'],
  ['bucketInstructionArgsErrorsAbi', 'BucketInstructionArgs.sol', 'BucketInstructionArgs'],
  ['bucketEngineAbi', 'BucketEngine.sol', 'BucketEngine'],
  ['bucketMathErrorsAbi', 'BucketMath.sol', 'BucketMath'],
  ['bucketPolicyErrorsAbi', 'BucketPolicyLib.sol', 'BucketPolicyLib'],
]

const lines = [
  '// Generated by scripts/lib/generate-abis.ts from Foundry artifacts. Do not edit.',
  '/* eslint-disable */',
  '',
]
for (const [exportName, file, contract] of artifacts) {
  const artifact = JSON.parse(readFileSync(join(out, file, `${contract}.json`), 'utf8')) as { abi: unknown[] }
  lines.push(`export const ${exportName} = ${JSON.stringify(artifact.abi, null, 2)} as const`, '')
}
mkdirSync(dirname(target), { recursive: true })
writeFileSync(target, lines.join('\n'))
console.log(`wrote ${artifacts.length} ABIs to ${target}`)
